# Numpy - Numerical Python

NumPy is a Python package. It stands for "Numerical Python". It is a library consisting of multidimensional array objects and a colletction of routines for processing of array.

Numpy - work for multidimensional data means Array

In [1]:
import numpy

In [2]:
 numpy.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
numpy.array([12.3,15.6,19.03])

array([12.3 , 15.6 , 19.03])

In [3]:
import numpy as np   #just gave short name numpy 

In [5]:
a=np.array([12,19,3,5])   #assing a varible to array like storing data in variable

In [6]:
a

array([12, 19,  3,  5])

In [8]:
b=np.array([12.3,15.6,19.03])

In [9]:
b

array([12.3 , 15.6 , 19.03])

In [10]:
a[1]

19

In [12]:
b[2]

19.03

In [13]:
b.size

3

In [15]:
b.dtype

dtype('float64')

In [16]:
a.dtype

dtype('int32')

2dimensional

In [19]:
a.dtype

dtype('int32')

In [24]:
c=np.array([[1,2],[3,4]]) #np.array([r1c1,r1c2],[r2c1,r2c2])

In [25]:
c

array([[1, 2],
       [3, 4]])

In [26]:
c.shape   #shape gives ------->  number of row and colums

(2, 2)

In [27]:
c.size    #size gives --------> number of elements

4

In [28]:
c.dtype    #dtype give --------> data type of elements

dtype('int32')

In [33]:
c.ndim   #ndim gives ----------->  no of dimensions

2

In [29]:
d=np.array([[1,2],[3,4],[5,6],[19,3]])

In [31]:
d

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [19,  3]])

In [32]:
d.shape

(4, 2)

In [34]:
e=np.array([[1,3,4],[2,5,7]])

In [35]:
e

array([[1, 3, 4],
       [2, 5, 7]])

In [36]:
e.shape

(2, 3)

In [37]:
e.size

6

In [38]:
e.ndim

2

In [40]:
f=np.array([[1,3,4],[2,5,7],[3,9,11]])

In [41]:
f

array([[ 1,  3,  4],
       [ 2,  5,  7],
       [ 3,  9, 11]])

In [42]:
f.ndim

2

In [43]:
f.shape

(3, 3)

In [44]:
f.itemsize  #itemsize is connected with datatype so 4 means int32

4

In [45]:
g=np.array([[1,3.19,4],[2,5,7],[3,9,11.19]])

In [46]:
g

array([[ 1.  ,  3.19,  4.  ],
       [ 2.  ,  5.  ,  7.  ],
       [ 3.  ,  9.  , 11.19]])

In [47]:
g.itemsize

8

In [48]:
g.dtype

dtype('float64')

In [50]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.arange(15).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [54]:
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [55]:
v=np.array([[1,3.19,4],[2,5,7],[3,9,11.19]])

In [56]:
v.ravel()

array([ 1.  ,  3.19,  4.  ,  2.  ,  5.  ,  7.  ,  3.  ,  9.  , 11.19])

In [57]:
i=np.array([[1,2],[3,4],[5,6],[19,3]])

In [58]:
i.ravel()

array([ 1,  2,  3,  4,  5,  6, 19,  3])

In [60]:
np.zeros([2,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [62]:
np.ones([3,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [64]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

# Broadcasting in NumPy

The term broadcasting decribes how NumPy treats arrays with different
shapes during arithemetic operations. Subject to certain constraints, 
the smaller array is "braodcast" accross the larger array so that they
have compatible shapes. Braodcasting provides a means of vectorizing
array operations.

In [70]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
a*b

array([ 6, 14, 24, 36, 50])

In [71]:
a+b

array([ 7,  9, 11, 13, 15])

In [66]:
a=np.array([1,2,3,4,5])
b=2
a*b

array([ 2,  4,  6,  8, 10])

In [67]:
a+b

array([3, 4, 5, 6, 7])

In [73]:
a=np.array([1,2,3,4,5])

In [74]:
a

array([1, 2, 3, 4, 5])

In [75]:
a**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [77]:
a**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [78]:
p=np.random.random([3,3])

In [79]:
p

array([[0.26661649, 0.31060741, 0.30594017],
       [0.13734742, 0.24980681, 0.79248056],
       [0.27410568, 0.1035745 , 0.25107523]])

Universal Functions:

In [80]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [81]:
np.add(a,b)

array([ 7,  9, 11, 13, 15])

In [82]:
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [83]:
a

array([1, 2, 3, 4, 5])

In [84]:
np.exp(8)

2980.9579870417283

Indexing,Slicing and Iterating

In [85]:
a   # array is already indexed

array([1, 2, 3, 4, 5])

In [86]:
a[2:5]  # slicing of arry ------> starts from 2 and end to 5 

array([3, 4, 5])

In [87]:
a[-1]

5

In [88]:
a[-2]

4

In [89]:
a[-4]

2

In [91]:
a[-4:-2]

array([2, 3])

In [93]:
v=np.arange(10)

In [94]:
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
v[-5]

5

In [96]:
v[-3:]  # Slicing from last 3 indext to till end of the array

array([7, 8, 9])

In [97]:
v[3:]  # slicing from indext 3 to till end of the array

array([3, 4, 5, 6, 7, 8, 9])

In [98]:
v1=np.array([np.nan,1,2,3,np.nan,19,6,24])  #np.nan means missing data

In [99]:
v1

array([nan,  1.,  2.,  3., nan, 19.,  6., 24.])

The random module provides nice functions to generate random numbers
(and also statistical distribution) of any given shape,random functino
will generate any number between 0 and 1

In [102]:
np.random.random([2,2])

array([[0.15697709, 0.48662643],
       [0.0839134 , 0.72056523]])

In [103]:
np.random.rand(2,2)  # unifrom distribrution ----> similar like random

array([[0.2266584 , 0.83068193],
       [0.0419561 , 0.39593846]])

In [104]:
np.random.randn(3,2)

array([[-0.94262634,  0.46388967],
       [ 0.18136631,  0.90072911],
       [ 0.59840661,  0.79498185]])

In [105]:
np.random.randn(2,3)

array([[-0.44061719,  0.16266997, -0.75569623],
       [-0.17545314,  1.69313257, -0.20983542]])